version: '3.3'

services:
  my-rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  my-mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  consumer-service:
    image: fredoliveirace/consumer-service
    depends_on:
      - my-rabbitmq
      - my-mongo
    ports:
      - "8081:8081"

  producer-service:
    image: fredoliveirace/producer-service
    depends_on:
      - my-rabbitmq
      - my-mongo
      - consumer-service
    ports:
      - "8082:8082"
