version: "3.3"

networks:
  messaging:
    external: true

services:
  my-rabbitmq:
    image: rabbitmq:management
    restart: always
    network_mode: host
    ports:
      - "5672:5672"
      - "15672:15672"

  my-mongo:
    image: mongo
    restart: always
    network_mode: host
    ports:
      - "27017:27017"

  consumer-service:
    image: fredoliveirace/consumer-service
    restart: always
    network_mode: host
    depends_on:
      - my-rabbitmq
      - my-mongo
    ports:
      - "8081:8081"

  producer-service:
    image: fredoliveirace/producer-service
    restart: always
    network_mode: host
    depends_on:
      - my-rabbitmq
      - my-mongo
      - consumer-service
    ports:
      - "8082:8082"
